title: Vertica Blog
description: Vertica Analytics Platform 소개 블로그
baseurl: "/vertica_blog"
url: "https://jin0326.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .venv
  - extract_pptx_text.py
  - Vertica_소개자료_202509.pptx
